# Generated by Django 3.0.8 on 2020-07-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_libr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/media/cars_photo'),
        ),
    ]
