# Generated by Django 3.0.8 on 2020-07-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_libr', '0003_auto_20200719_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('механика', 'механика'), ('автомат', 'автомат'), ('робот', 'робот')], default=1),
        ),
    ]
